version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    ports: 
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=t4tt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./project/:/usr/src/app/
    ports:
      - 80:80
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - db
    links:
      - redis
  redis:
    image: redis:alpine

volumes:
  postgres_data: