# Generated by Django 3.0.5 on 2020-10-07 19:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200922_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='main_data',
        ),
        migrations.AddField(
            model_name='score',
            name='cor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], size=10),
        ),
        migrations.AddField(
            model_name='score',
            name='cor_cli',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], size=10),
        ),
        migrations.AddField(
            model_name='score',
            name='incor_cli',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], size=10),
        ),
        migrations.AddField(
            model_name='score',
            name='time_t',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True), default=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], size=10),
        ),
        migrations.AddField(
            model_name='score',
            name='total_cli',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], size=10),
        ),
        migrations.AlterField(
            model_name='score',
            name='computed_nums',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True), default=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], size=1),
        ),
    ]
