# Generated by Django 3.0.5 on 2020-11-12 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20201007_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='default.jpg', upload_to='spinner_pics')),
                ('image2', models.ImageField(default='default.jpg', upload_to='spinner_pics')),
                ('image3', models.ImageField(default='default.jpg', upload_to='spinner_pics')),
                ('image4', models.ImageField(default='default.jpg', upload_to='spinner_pics')),
                ('image5', models.ImageField(default='default.jpg', upload_to='spinner_pics')),
                ('image6', models.ImageField(default='default.jpg', upload_to='spinner_pics')),
                ('image7', models.ImageField(default='default.jpg', upload_to='spinner_pics')),
                ('image8', models.ImageField(default='default.jpg', upload_to='spinner_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
