# Generated by Django 3.0.5 on 2020-11-22 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_spinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinner',
            name='image1',
            field=models.ImageField(default='pikachu.jpg', upload_to='media/main_nav/spinner_pics'),
        ),
        migrations.AlterField(
            model_name='spinner',
            name='image2',
            field=models.ImageField(default='pikachu.jpg', upload_to='spinner_pics'),
        ),
        migrations.AlterField(
            model_name='spinner',
            name='image3',
            field=models.ImageField(default='pikachu.jpg', upload_to='spinner_pics'),
        ),
        migrations.AlterField(
            model_name='spinner',
            name='image4',
            field=models.ImageField(default='pikachu.jpg', upload_to='spinner_pics'),
        ),
        migrations.AlterField(
            model_name='spinner',
            name='image5',
            field=models.ImageField(default='pikachu.jpg', upload_to='spinner_pics'),
        ),
        migrations.AlterField(
            model_name='spinner',
            name='image6',
            field=models.ImageField(default='pikachu.jpg', upload_to='spinner_pics'),
        ),
        migrations.AlterField(
            model_name='spinner',
            name='image7',
            field=models.ImageField(default='pikachu.jpg', upload_to='spinner_pics'),
        ),
        migrations.AlterField(
            model_name='spinner',
            name='image8',
            field=models.ImageField(default='pikachu.jpg', upload_to='spinner_pics'),
        ),
        migrations.CreateModel(
            name='voice_game4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(default='pikachu.jpg', upload_to='media/main_nav/custom_game')),
                ('pic2', models.ImageField(default='pikachu.jpg', upload_to='media/main_nav/custom_game')),
                ('pic3', models.ImageField(default='pikachu.jpg', upload_to='media/main_nav/custom_game')),
                ('pic4', models.ImageField(default='pikachu.jpg', upload_to='media/main_nav/custom_game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='voice_game3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(default='pikachu.jpg', upload_to='media/main_nav/custom_game')),
                ('pic2', models.ImageField(default='pikachu.jpg', upload_to='media/main_nav/custom_game')),
                ('pic3', models.ImageField(default='pikachu.jpg', upload_to='media/main_nav/custom_game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='voice_game2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(default='pikachu.jpg', upload_to='media/main_nav/custom_game')),
                ('pic2', models.ImageField(default='pikachu.jpg', upload_to='media/main_nav/custom_game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
