# Generated by Django 3.0.5 on 2020-11-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_voice_words2'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice_words2',
            name='word0',
            field=models.CharField(default='Custom Game', max_length=30),
        ),
    ]
