# Generated by Django 3.0.5 on 2020-11-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_voice_words2_word0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voice_words2',
            old_name='word0',
            new_name='title',
        ),
    ]
