# Generated by Django 3.0.5 on 2020-11-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201127_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice_record',
            name='record1',
        ),
        migrations.RemoveField(
            model_name='voice_record',
            name='record2',
        ),
        migrations.RemoveField(
            model_name='voice_record',
            name='record3',
        ),
        migrations.RemoveField(
            model_name='voice_record',
            name='record4',
        ),
        migrations.RemoveField(
            model_name='voice_record',
            name='record5',
        ),
        migrations.AddField(
            model_name='voice_record',
            name='notes',
            field=models.TextField(default='This is the session notes for the pop game'),
        ),
    ]
