# Generated by Django 3.0.5 on 2020-11-27 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_auto_20201127_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='voice_record_pancake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(blank=True, null=True)),
                ('incorrect', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(default='This is the session notes for the pancake game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='voice_record_light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(blank=True, null=True)),
                ('incorrect', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(default='This is the session notes for the light game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='voice_record_cookies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(blank=True, null=True)),
                ('incorrect', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(default='This is the session notes for the cookies game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
