# Generated by Django 3.0.5 on 2020-11-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_voice_record_cookies_voice_record_light_voice_record_pancake'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice_record',
            name='date',
            field=models.CharField(default='2020-11-27', max_length=30),
        ),
        migrations.AddField(
            model_name='voice_record_cookies',
            name='date',
            field=models.CharField(default='2020-11-27', max_length=30),
        ),
        migrations.AddField(
            model_name='voice_record_light',
            name='date',
            field=models.CharField(default='2020-11-27', max_length=30),
        ),
        migrations.AddField(
            model_name='voice_record_pancake',
            name='date',
            field=models.CharField(default='2020-11-27', max_length=30),
        ),
    ]
