# Generated by Django 3.0.5 on 2020-11-27 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201127_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice_record',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='voice_record_cookies',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='voice_record_light',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='voice_record_pancake',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
