# Generated by Django 3.0.5 on 2020-11-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201127_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='voice_record',
        ),
    ]
