# Generated by Django 3.0.5 on 2020-11-27 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_delete_voice_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='voice_record_pop',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('correct', models.IntegerField(blank=True, null=True)),
                ('incorrect', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(default='This is the session notes for the pop game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
