# Generated by Django 3.0.5 on 2020-11-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_voice_record_pop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice_record_pop',
            name='session_id',
        ),
        migrations.AddField(
            model_name='voice_record_pop',
            name='id',
            field=models.AutoField(auto_created=True,primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voice_record_light',
            name='notes',
            field=models.TextField(default='This is the session notes for the pop game'),
        ),
    ]
