# Generated by Django 3.0.5 on 2020-11-28 21:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_auto_20201128_1929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='voice_record_light',
            new_name='VoiceRecordLight',
        ),
        migrations.RenameModel(
            old_name='voice_record_pop',
            new_name='VoiceRecordPop',
        ),
    ]
