# Generated by Django 3.0.5 on 2020-11-29 00:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_auto_20201128_2118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoiceRecordLight',
            new_name='Record',
        ),
    ]
